POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/f8f2cfca-9ff1-44dc-a8b1-2daed9dac318